### ISSUE TITLE
sdb-0.10.5 fails on VoidLinux

### ISSUE THREAD

**Issue by Gottox** [radare/sdb#118]
I'm unable to set the correct CFLAGS for the cdb._o file.

template file: https://gist.github.com/75769142daa0d110788168e4e3e50770

buildlog: https://gist.github.com/Gottox/723be782df3119064ff720de03f777a5

Do you know where this file is generated?

**Comment by radare** [comment]
0.10.5 is kinda old, i didnt released 0.10.6 because it was breaking r2, and im not preparing a new release that should bump.

i see that the cflags are honored. but its failing because you are using that cflags.

you may wanna try with latest sdb from git

**Comment by radare** [comment]
ah i think this is because the object file is named ._o instead of .o so make doesnt know how to pass the cflags

**Comment by radare** [comment]
try https://github.com/radare/sdb/commit/12b2945bc2ff978ad1846408851ae31d8eaecb4c

**Comment by trufae** [comment]
please try with 0.11.0
