### ISSUE TITLE
SDB Makefile has not granular configuration to package for libraries

### ISSUE THREAD

**Issue by xambroz** [radare/sdb#89]
Hello, 
the SDB makefile doesn't make it easy to configure the locations of directories. 
It allows for defining prefix and destdir, but would not allow to change the libs directory.
Way how is it used combined in the PFX variable makes it difficult to configure the name of the lib (/usr/lib64 for example) directory itself.

It would make packaging easier to include these possibilities in some way similiar as autoconf toolset does. It is especially needed for the LIBDIR.

Please could you consider including this patch to the upstream SDB?:
https://rebus.fedorapeople.org/SOURCES/sdb-dirs.patch

What it does it:
- adds config.mk with variables BINDIR, LIBDIR, DATADIR. INCDIR
- moves MANDIR, VAPIDIR to config.mk and removes DESTDIR from there
- makes use of the DESTDIR only in the install/sysmstall/uninstall sections
- adds the ldconfig symbolic link (needed for rpm package and I guess it is usefull elsewhere as well)

Best regards
Michal Ambroz

**Comment by radare** [comment]
Thanks! i have included this patch into the master branch. Will be included in the next release, that will happen soon :)

**Comment by xambroz** [comment]
Thank you.
